from analyzers.framework import detect_framework
from analyzers.structure import analyze_structure
from analyzers.ast_analyzer import analyze_ast
from analyzers.training_loop import analyze_training_loop
from analyzers.config_extractor import extract_configs
from analyzers.dependency import analyze_dependencies
from analyzers.readme_parser import parse_readme
from analyzers.reproducibility import score_reproducibility
