#!/usr/bin/env python3
"""
Beamer Report Generator — Generate a Beamer LaTeX presentation
from result-analyzer's beamer_report_data.json.

Usage:
    python generate_beamer_report.py beamer_report_data.json -o reproduction_slides.tex
    python generate_beamer_report.py beamer_report_data.json -o slides.tex --compile
"""
import json
import os
import sys
import argparse
import subprocess
from typing import Dict, List


PREAMBLE = r"""\documentclass[aspectratio=169,10pt]{beamer}

\usetheme{Madrid}
\usecolortheme{default}
\setbeamertemplate{navigation symbols}{}
\setbeamertemplate{footline}[frame number]

\usepackage{amsmath,amssymb,booktabs}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{xcolor}

% Semantic colors
\definecolor{positive}{HTML}{0173B2}
\definecolor{negative}{HTML}{DE8F05}
\definecolor{emphasis}{HTML}{029E73}
\definecolor{passcolor}{HTML}{2E7D32}
\definecolor{warncolor}{HTML}{F57F17}
\definecolor{failcolor}{HTML}{C62828}

\newcommand{\pass}[1]{\textcolor{passcolor}{#1}}
\newcommand{\warn}[1]{\textcolor{warncolor}{#1}}
\newcommand{\fail}[1]{\textcolor{failcolor}{#1}}
"""


def escape_latex(s: str) -> str:
    """Escape special LaTeX characters."""
    if not s:
        return ''
    replacements = [
        ('\\', r'\textbackslash{}'),
        ('&', r'\&'),
        ('%', r'\%'),
        ('$', r'\$'),
        ('#', r'\#'),
        ('_', r'\_'),
        ('{', r'\{'),
        ('}', r'\}'),
        ('~', r'\textasciitilde{}'),
        ('^', r'\textasciicircum{}'),
    ]
    # Don't escape emoji — XeLaTeX handles them
    result = s
    for old, new in replacements:
        result = result.replace(old, new)
    return result


def status_to_latex(status_str: str) -> str:
    """Convert status string with emoji to colored LaTeX."""
    s = status_str.strip()
    if 'PASS' in s:
        return r'\pass{PASS}'
    elif 'WARN' in s:
        return r'\warn{WARN}'
    elif 'FAIL' in s:
        return r'\fail{FAIL}'
    return escape_latex(s)


def generate_title_slide(slide: Dict) -> str:
    """Generate a title slide."""
    title = escape_latex(slide.get('title', 'Reproduction Report'))
    subtitle = slide.get('subtitle', '')
    # Convert emoji overall status
    if 'FAIL' in subtitle:
        subtitle_tex = r'\fail{Overall: FAIL}'
    elif 'PASS' in subtitle:
        subtitle_tex = r'\pass{Overall: PASS}'
    elif 'WARN' in subtitle:
        subtitle_tex = r'\warn{Overall: WARN}'
    else:
        subtitle_tex = escape_latex(subtitle)

    return rf"""
\title{{{title}}}
\subtitle{{{subtitle_tex}}}
\author{{Generated by result-analyzer}}
\date{{\today}}

\begin{{frame}}
\titlepage
\end{{frame}}
"""


def generate_table_slide(slide: Dict) -> str:
    """Generate a metric comparison table slide."""
    title = escape_latex(slide.get('title', 'Results'))
    headers = slide.get('headers', [])
    rows = slide.get('rows', [])

    if not rows:
        return ''

    # Build table
    n_cols = len(headers)
    col_spec = 'l' + 'c' * (n_cols - 1)

    lines = []
    lines.append(rf'\begin{{frame}}{{{title}}}')
    lines.append(r'\vspace{4pt}')
    lines.append(r'\begin{center}')
    lines.append(rf'\begin{{tabular}}{{{col_spec}}}')
    lines.append(r'\toprule')

    # Headers
    header_tex = ' & '.join(rf'\textbf{{{escape_latex(h)}}}' for h in headers)
    lines.append(header_tex + r' \\')
    lines.append(r'\midrule')

    # Rows
    for row in rows:
        cells = []
        for key in ['metric', 'paper', 'reproduced', 'diff', 'status']:
            val = row.get(key, '')
            if key == 'status':
                cells.append(status_to_latex(val))
            elif key == 'diff':
                # Color the diff
                diff_str = str(val)
                if diff_str.startswith('+'):
                    cells.append(rf'\warn{{{escape_latex(diff_str)}}}')
                elif diff_str.startswith('-'):
                    cells.append(rf'\pass{{{escape_latex(diff_str)}}}')
                else:
                    cells.append(escape_latex(diff_str))
            else:
                cells.append(escape_latex(str(val)))
        lines.append(' & '.join(cells) + r' \\')

    lines.append(r'\bottomrule')
    lines.append(r'\end{tabular}')
    lines.append(r'\end{center}')
    lines.append(r'\end{frame}')

    return '\n'.join(lines)


def generate_figure_slide(slide: Dict) -> str:
    """Generate a figure slide."""
    title = escape_latex(slide.get('title', 'Figure'))
    fig_path = slide.get('figure_path', '')

    if not fig_path or not os.path.exists(fig_path):
        return ''

    # Convert to relative path
    fig_path_tex = fig_path.replace('\\', '/')

    return rf"""
\begin{{frame}}{{{title}}}
\begin{{center}}
\includegraphics[width=0.85\textwidth,height=0.75\textheight,keepaspectratio]{{{fig_path_tex}}}
\end{{center}}
\end{{frame}}
"""


def generate_conclusion_slide(slide: Dict) -> str:
    """Generate a conclusion slide."""
    overall = slide.get('overall_status', 'N/A')
    passed = slide.get('passed', 0)
    total = slide.get('total', 0)

    if overall == 'PASS':
        status_tex = r'\pass{\textbf{PASS}}'
        icon = r'\pass{$\checkmark$}'
    elif overall == 'WARN':
        status_tex = r'\warn{\textbf{WARN}}'
        icon = r'\warn{$\sim$}'
    elif overall == 'FAIL':
        status_tex = r'\fail{\textbf{FAIL}}'
        icon = r'\fail{$\times$}'
    else:
        status_tex = escape_latex(overall)
        icon = ''

    return rf"""
\begin{{frame}}{{Conclusion}}
\begin{{center}}
\vspace{{1cm}}

{{\Huge {icon}}}

\vspace{{0.5cm}}

{{\Large Overall Status: {status_tex}}}

\vspace{{0.5cm}}

{{\large {passed}/{total} key metrics within tolerance}}

\vspace{{1cm}}

\textcolor{{gray}}{{\small Report generated by \texttt{{result-analyzer}} · \today}}
\end{{center}}
\end{{frame}}

\begin{{frame}}
\begin{{center}}
\vspace{{2cm}}
{{\Huge Thank You}}

\vspace{{1cm}}
{{\large Questions?}}
\end{{center}}
\end{{frame}}
"""


def generate_beamer_tex(json_path: str, output_path: str) -> str:
    """
    Generate a complete Beamer .tex file from beamer_report_data.json.

    Args:
        json_path: Path to beamer_report_data.json
        output_path: Path to output .tex file

    Returns:
        Path to the generated .tex file
    """
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    slides = data.get('slides', [])
    if not slides:
        print("  ⚠️ No slides found in JSON")
        return ''

    tex_parts = [PREAMBLE, r'\begin{document}', '']

    for slide in slides:
        slide_type = slide.get('type', '')

        if slide_type == 'title':
            tex_parts.append(generate_title_slide(slide))
        elif slide_type == 'table':
            tex_parts.append(generate_table_slide(slide))
        elif slide_type == 'figure':
            tex_parts.append(generate_figure_slide(slide))
        elif slide_type == 'conclusion':
            tex_parts.append(generate_conclusion_slide(slide))

    tex_parts.append(r'\end{document}')

    tex_content = '\n'.join(tex_parts)

    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else '.', exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(tex_content)

    print(f"  ✅ Generated: {output_path}")
    return output_path


def compile_beamer(tex_path: str) -> bool:
    """Compile the Beamer .tex to PDF using XeLaTeX."""
    tex_dir = os.path.dirname(tex_path) or '.'
    tex_name = os.path.basename(tex_path)

    for pass_num in range(2):
        result = subprocess.run(
            ['xelatex', '-interaction=nonstopmode', tex_name],
            cwd=tex_dir,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            print(f"  ❌ XeLaTeX pass {pass_num+1} failed")
            print(result.stderr[-500:] if result.stderr else '')
            return False

    pdf_path = tex_path.replace('.tex', '.pdf')
    if os.path.exists(pdf_path):
        print(f"  ✅ Compiled: {pdf_path}")
        return True
    return False


def main():
    parser = argparse.ArgumentParser(
        description='Generate Beamer slides from result-analyzer JSON'
    )
    parser.add_argument('json_file', help='Path to beamer_report_data.json')
    parser.add_argument('-o', '--output', default='reproduction_slides.tex',
                        help='Output .tex file path')
    parser.add_argument('--compile', action='store_true',
                        help='Also compile to PDF (requires XeLaTeX)')

    args = parser.parse_args()

    if not os.path.exists(args.json_file):
        print(f"Error: {args.json_file} not found")
        sys.exit(1)

    tex_path = generate_beamer_tex(args.json_file, args.output)

    if args.compile and tex_path:
        compile_beamer(tex_path)


if __name__ == '__main__':
    main()
