#!/usr/bin/env python3
"""
code-writer — Generate implementation code scaffolding from paper descriptions.

Usage:
    python generate.py --paper paper_content.json -o project/
    python generate.py --describe "A diffusion model for image generation" -o project/
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from extractors.paper_info import extract_paper_info, extract_from_markdown
from extractors.architecture import extract_architecture
from extractors.equations import extract_equations
from extractors.experiment import extract_experiment
from extractors.reference_finder import find_reference_code


def generate_project(paper_data: dict, output_dir: str, framework: str = "pytorch"):
    """
    Generate a project scaffolding from extracted paper information.

    Args:
        paper_data: Extracted paper info (from extract_paper_info)
        output_dir: Directory to write generated project
        framework: Target framework (pytorch/tensorflow/jax)
    """
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(os.path.join(output_dir, "src"), exist_ok=True)
    os.makedirs(os.path.join(output_dir, "configs"), exist_ok=True)
    os.makedirs(os.path.join(output_dir, "references"), exist_ok=True)

    # Extract all info
    arch = extract_architecture(
        paper_data.get('sections', []),
        paper_data.get('full_text', '')
    )
    exp = extract_experiment(
        paper_data.get('sections', []),
        paper_data.get('full_text', '')
    )
    refs = find_reference_code(paper_data)

    title = paper_data.get('title', 'UnnamedModel')
    model_name = arch.get('model_name', '') or _title_to_class_name(title)

    hp = exp.get('hyperparameters', {})

    # ── Generate config ──
    config = {
        'model': {
            'name': model_name,
            'architecture': arch.get('architecture_type', 'unknown'),
            'components': arch.get('components', []),
        },
        'training': {
            'learning_rate': float(hp.get('learning_rate', '1e-3')),
            'batch_size': int(hp.get('batch_size', '32')),
            'epochs': int(hp.get('epochs', '100')),
            'optimizer': hp.get('optimizer', 'Adam'),
            'weight_decay': float(hp.get('weight_decay', '0')),
            'seed': int(hp.get('seed', '42')),
        },
        'data': {
            'datasets': exp.get('datasets', []),
            'input_size': 32,
        },
        'evaluation': {
            'metrics': exp.get('metrics', []),
        },
    }

    with open(os.path.join(output_dir, "configs", "default.yaml"), 'w', encoding='utf-8') as f:
        import yaml
        yaml.dump(config, f, default_flow_style=False, allow_unicode=True)

    # ── Generate model.py ──
    _write_model_py(output_dir, model_name, arch, title)

    # ── Generate train.py ──
    _write_train_py(output_dir, model_name, config['training'])

    # ── Generate data.py ──
    _write_data_py(output_dir, model_name, config)

    # ── Generate requirements.txt ──
    _write_requirements(output_dir, framework)

    # ── Generate README ──
    _write_readme(output_dir, title, model_name, config)

    # ── Generate reference discovery plan ──
    _write_reference_plan(output_dir, refs)

    # ── Generate implementation checklist ──
    _write_checklist(output_dir, title, arch, exp)

    # Print summary
    print(f"\n{'═' * 60}")
    print(f"  📂 Project generated: {output_dir}")
    print(f"  🏷️  Model: {model_name}")
    print(f"  🔧 Framework: {framework}")
    print(f"  🧱 Components: {', '.join(arch.get('components', ['unknown']))}")
    print(f"  📊 Datasets: {', '.join(exp.get('datasets', ['not specified']))}")
    print(f"  📐 Equations found: {len(paper_data.get('equations', []))}")
    print(f"  🔗 Base methods: {', '.join(refs.get('base_methods', ['none']))}")
    print(f"{'═' * 60}")
    print(f"\n  Next steps:")
    print(f"  1. Read references/search_plan.md and find reference code")
    print(f"  2. Fill in TODO markers in src/model.py")
    print(f"  3. Implement data loading in src/data.py")
    print(f"  4. Run: cd {output_dir} && pip install -r requirements.txt")
    print(f"  5. Test: python src/train.py --epochs 1")


def _title_to_class_name(title: str) -> str:
    """Convert paper title to a Python class name."""
    words = title.split()[:3]
    name = ''.join(w.capitalize() for w in words if w.isalpha())
    return name or 'Model'


def _write_model_py(output_dir, model_name, arch, title):
    components = arch.get('components', [])
    code = f'''"""Model definition for {model_name}
Paper: {title}
Generated by code-writer skill
"""
import torch
import torch.nn as nn
import torch.nn.functional as F


'''
    # Generate component classes based on detected architecture
    for comp in components:
        class_name = comp.replace(' ', '').title() + 'Block'
        code += f'''class {class_name}(nn.Module):
    """TODO: Implement {comp} component based on paper description."""
    def __init__(self):
        super().__init__()
        # TODO: Define layers for {comp}
        pass

    def forward(self, x):
        # TODO: Implement {comp} forward pass
        return x


'''

    code += f'''class {model_name}(nn.Module):
    """{title}

    Architecture components: {', '.join(components)}

    TODO: Implement the full model by connecting components.
    """
    def __init__(self):
        super().__init__()
        # TODO: Initialize model components
'''
    for comp in components:
        class_name = comp.replace(' ', '').title() + 'Block'
        var_name = comp.replace(' ', '_').lower()
        code += f'        # self.{var_name} = {class_name}()\n'

    code += f'''
    def forward(self, x):
        """
        Args:
            x: Input tensor
        Returns:
            Output tensor
        """
        # TODO: Connect components
        return x
'''

    with open(os.path.join(output_dir, "src", "model.py"), 'w', encoding='utf-8') as f:
        f.write(code)


def _write_train_py(output_dir, model_name, training_config):
    lr = training_config.get('learning_rate', 1e-3)
    bs = training_config.get('batch_size', 32)
    epochs = training_config.get('epochs', 100)
    opt = training_config.get('optimizer', 'Adam')
    seed = training_config.get('seed', 42)

    code = f'''"""Training script for {model_name}
Generated by code-writer skill
"""
import os
import random
import argparse
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from model import {model_name}
from data import get_dataloader


def set_seed(seed={seed}):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def train(args):
    set_seed(args.seed)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {{device}}")

    # Data
    train_loader = get_dataloader(split="train", batch_size=args.batch_size)

    # Model
    model = {model_name}().to(device)
    params = sum(p.numel() for p in model.parameters())
    print(f"Model parameters: {{params:,}}")

    # Optimizer
    optimizer = torch.optim.{opt}(model.parameters(), lr=args.lr)

    # Loss — TODO: Replace with paper-specific loss
    criterion = nn.MSELoss()

    # Training loop
    for epoch in range(args.epochs):
        model.train()
        total_loss = 0

        for batch_idx, (inputs, targets) in enumerate(train_loader):
            inputs, targets = inputs.to(device), targets.to(device)

            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

            if batch_idx % 50 == 0:
                print(f"  Epoch {{epoch+1}} [{{batch_idx}}/{{len(train_loader)}}] Loss: {{loss.item():.6f}}")

        avg_loss = total_loss / max(len(train_loader), 1)
        print(f"Epoch {{epoch+1}}/{{args.epochs}} — Loss: {{avg_loss:.6f}}")

        # Save checkpoint
        os.makedirs(args.save_dir, exist_ok=True)
        torch.save(model.state_dict(), os.path.join(args.save_dir, "latest.pt"))

    print("Training complete!")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--lr", type=float, default={lr})
    parser.add_argument("--batch-size", type=int, default={bs})
    parser.add_argument("--epochs", type=int, default={epochs})
    parser.add_argument("--seed", type=int, default={seed})
    parser.add_argument("--save-dir", default="checkpoints")
    args = parser.parse_args()
    train(args)
'''
    with open(os.path.join(output_dir, "src", "train.py"), 'w', encoding='utf-8') as f:
        f.write(code)


def _write_data_py(output_dir, model_name, config):
    bs = config['training']['batch_size']
    datasets = config['data'].get('datasets', [])
    ds_str = ', '.join(datasets) if datasets else 'custom'

    code = f'''"""Data loading for {model_name}
Datasets: {ds_str}
Generated by code-writer skill
"""
import torch
from torch.utils.data import Dataset, DataLoader


class PaperDataset(Dataset):
    """
    TODO: Implement dataset loading for {ds_str}.

    Steps:
    1. Download/prepare the dataset
    2. Implement __len__ and __getitem__
    3. Add appropriate transforms
    """
    def __init__(self, split="train"):
        self.split = split
        # PLACEHOLDER — replace with real data
        self.data = torch.randn(100, 3, 32, 32)
        self.labels = torch.randint(0, 10, (100,))
        print(f"[{{split}}] Loaded {{len(self)}} samples (PLACEHOLDER)")

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]


def get_dataloader(split="train", batch_size={bs}, num_workers=4):
    dataset = PaperDataset(split=split)
    return DataLoader(
        dataset, batch_size=batch_size,
        shuffle=(split == "train"),
        num_workers=num_workers,
        pin_memory=True,
    )
'''
    with open(os.path.join(output_dir, "src", "data.py"), 'w', encoding='utf-8') as f:
        f.write(code)


def _write_requirements(output_dir, framework):
    reqs = {
        'pytorch': 'torch\ntorchvision\nnumpy\npyyaml\ntqdm\n',
        'tensorflow': 'tensorflow\nnumpy\npyyaml\ntqdm\n',
        'jax': 'jax\njaxlib\nflax\noptax\nnumpy\npyyaml\ntqdm\n',
    }
    with open(os.path.join(output_dir, "requirements.txt"), 'w', encoding='utf-8') as f:
        f.write(reqs.get(framework, reqs['pytorch']))


def _write_readme(output_dir, title, model_name, config):
    hp = config['training']
    ds = ', '.join(config['data'].get('datasets', ['custom']))
    readme = f"""# {model_name}

Implementation of: **{title}**

Generated by [code-writer](../code-writer/) skill.

## Quick Start

```bash
pip install -r requirements.txt
cd src
python train.py
```

## Configuration

See `configs/default.yaml` for hyperparameters:
- Learning rate: {hp['learning_rate']}
- Batch size: {hp['batch_size']}
- Epochs: {hp['epochs']}
- Optimizer: {hp['optimizer']}

## Dataset

{ds}

## TODO

- [ ] Implement model architecture in `src/model.py`
- [ ] Implement data loading in `src/data.py`
- [ ] Implement paper-specific loss function
- [ ] Verify with small overfit test
- [ ] Full training run
"""
    with open(os.path.join(output_dir, "README.md"), 'w', encoding='utf-8') as f:
        f.write(readme)


def _write_reference_plan(output_dir, refs):
    plan = f"""# 🔍 Reference Code Search Plan

## Base Methods Detected

{chr(10).join('- ' + m for m in refs.get('base_methods', ['None detected']))}

## Search Queries

Use **paper-finder** with these queries to find reference implementations:

"""
    for q in refs.get('search_queries', []):
        plan += f"### {q['reason']}\n"
        plan += f"- Query: `{q['query']}`\n"
        plan += f"- Source: {q['source']}\n\n"

    plan += f"""## Strategy

{refs.get('strategy', 'Search for related papers with code.')}

## After Finding Code

1. Clone the reference repo
2. Run `code-analyzer` on it to understand the structure
3. Identify reusable components (model blocks, training loops)
4. Adapt them for this paper's specific modifications
"""

    with open(os.path.join(output_dir, "references", "search_plan.md"), 'w', encoding='utf-8') as f:
        f.write(plan)


def _write_checklist(output_dir, title, arch, exp):
    checklist = f"""# Implementation Checklist — {title}

## Phase 0: Reference Code Discovery
- [ ] Read `references/search_plan.md`
- [ ] Search for base method implementations
- [ ] Clone and analyze reference repos with `code-analyzer`
- [ ] Identify reusable components

## Phase 1: Data Pipeline
- [ ] Download/prepare dataset
- [ ] Implement `src/data.py` Dataset class
- [ ] Verify: `print(next(iter(loader)).shape)` matches expected dimensions
- [ ] Add data augmentation if mentioned in paper

## Phase 2: Model Components
- [ ] Implement each component as a separate `nn.Module`
- [ ] Test each component individually with dummy tensors
- [ ] Verify input/output dimensions match paper description
{chr(10).join('- [ ] Component: ' + c for c in arch.get('components', []))}

## Phase 3: Full Model
- [ ] Connect all components in the main model class
- [ ] Verify: `model(dummy_input).shape` is correct
- [ ] Check parameter count against paper (if reported)

## Phase 4: Loss Function
- [ ] Implement paper-specific loss (use `formula2code` for equations)
- [ ] Verify loss is a scalar

## Phase 5: Training
- [ ] Overfit on 5 samples → loss should approach 0
- [ ] Check gradient flow (no NaN/Inf)
- [ ] Full training run
- [ ] Compare metrics with paper's Table 1

## Phase 6: Evaluation
{chr(10).join('- [ ] Metric: ' + m for m in exp.get('metrics', ['accuracy']))}

## Common Debugging
- Weight initialization: check if paper specifies (e.g., Xavier, Kaiming)
- Normalization: [0,1] or [-1,1]? BatchNorm or LayerNorm?
- Learning rate schedule: warmup? cosine decay?
- Gradient clipping: mentioned in paper?
"""
    with open(os.path.join(output_dir, "implementation_checklist.md"), 'w', encoding='utf-8') as f:
        f.write(checklist)


def main():
    parser = argparse.ArgumentParser(description='Generate code from paper')
    parser.add_argument('--paper', help='Path to paper-parser JSON output')
    parser.add_argument('--markdown', help='Path to paper markdown')
    parser.add_argument('--describe', help='Text description of the paper/model')
    parser.add_argument('-o', '--output', required=True, help='Output directory')
    parser.add_argument('--framework', choices=['pytorch', 'tensorflow', 'jax'],
                        default='pytorch')

    args = parser.parse_args()

    if args.paper:
        paper_data = extract_paper_info(args.paper)
    elif args.markdown:
        paper_data = extract_from_markdown(args.markdown)
    elif args.describe:
        paper_data = {
            'title': args.describe,
            'sections': [],
            'references': [],
            'full_text': args.describe,
        }
    else:
        parser.print_help()
        return

    generate_project(paper_data, args.output, args.framework)


if __name__ == '__main__':
    main()
